apps/accounts/urls.py
from django.urls import path, re_path
from .views import SignUpView, AccountUpdateView, logout_view, activate, send_activation_email
from django.contrib.auth.views import LoginView


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    re_path(
        r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate,
        name='activate'
    ),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('send_activation_email/', send_activation_email, name='send_activation_email'),
    path('settings/', AccountUpdateView.as_view(), name='settings'),
]

apps/courses/urls.py
from django.urls import path, include
from .views import (
    CourseListView,
    CourseDetailView,
    StudentCourseListView,
    course_enroll,
    LessonListView,
    LessonDetailView
 )


app_name = 'courses'
urlpatterns = [
    path('courses/', CourseListView.as_view(), name='list'),
    path('my_courses/', StudentCourseListView.as_view(), name='my_courses'),
    path('lessons/<slug:slug>', LessonListView.as_view(), name='lessons'),
    path('lessons/<slug:slug>/<slug:lesson_slug>', LessonDetailView.as_view(), name='lesson'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='detail'),
    path('users/', include('apps.course_users.urls', namespace="users")),
    path('enroll/<slug:slug>', course_enroll, name="enroll"),

]

it_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from it_courses import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('education/', include('apps.courses.urls', namespace="courses")),
    path('control_panel/', include('apps.control_panel.urls', namespace='control')),
    path('quiz/', include('apps.quizzes.urls', namespace='quiz')),

    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),

    path('', include('apps.main.urls', namespace="main")),

]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from it_courses.settings import SITE_URL
from .tokens import account_activation_token
from django.core.exceptions import ObjectDoesNotExist


class ITUser(AbstractUser):
    phone = models.CharField("Телефонный номер", max_length=20)
    birthday = models.DateField("День рождения")
    email = models.EmailField("email", unique=True)
    email_confirmed = models.BooleanField("Почта подтверждена", default=False)

    REQUIRED_FIELDS = ['email', 'phone', 'birthday']

    def send_activation_email(self):
        subject = 'Подтвердите почту для продолжения работы на ITCourses.'
        message = render_to_string('emails/account_activation_email.html', {
            'user': self,
            'domain': SITE_URL,
            'uid': urlsafe_base64_encode(force_bytes(self.pk)).decode('unicode_escape'),
            'token': account_activation_token.make_token(self),
        })
        self.email_user(subject, message)

    def is_student(self):
        try:
            if self.student:
                return True
            else:
                return False
        except ObjectDoesNotExist:
            return False

    def is_teacher(self):
        try:
            if self.teacher:
                return True
            else:
                return False
        except ObjectDoesNotExist:
            return False

    def is_active_student(self):
        if self.is_student():
            if self.student.get_open_curses().count() > 0:
                return True
        return False

apps/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'birthday',
            'email',
            'phone',
            'password1',
            'password2')
        widgets = {
            'birthday': DateInput()
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()
        user.send_activation_email()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'birthday',
            'phone',
        )
        widgets = {
            'birthday': DateInput()
        }

apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout
from django.shortcuts import HttpResponseRedirect, reverse, redirect
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView

from .forms import SignUpForm, UserUpdateForm
from .tokens import account_activation_token


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        messages.info(self.request, 'Вы успешно зарегистрировались. Теперь вы можете войти.')
        return reverse("accounts:login")


class AccountUpdateView(UpdateView):
    form_class = UserUpdateForm
    template_name = 'accounts/settings.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        messages.success(self.request, 'Данные успешно изменены')
        return reverse('accounts:settings')


def logout_view(request):
    logout(request)
    messages.info(request, 'Вы вышли из акаунта')
    return HttpResponseRedirect('/')


def activate(request, uidb64, token):
    user_model = get_user_model()
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = user_model.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user_model.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.email_confirmed = True
        user.save()
        login(request, user)
        messages.success(request, 'Вы успешно подтвердили почту!')
    else:
        messages.error(request, 'Ошибка при подтверждении почты, попробуйте еще раз')
    return redirect('main:home')


def send_activation_email(request):
    user = request.user
    user.send_activation_email()
    messages.info(request, 'Активация отправлена на почту')
    return redirect('main:home')

templates/accounts/account_activation_invalid.html
{% extends 'base.html' %}

{% block title %}Ошибка подтверждения почты{% endblock %}

{% block content %}
    <h2 class="title">Ошибка подтверждения почты</h2>
    <a href="{% url 'accounts:send_activation_email' %}">Подтвердить почту еще раз?</a>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Аутентификация{% endblock %}

{% block content %}
    <h2 class="title">Аутентификация</h2>
    {% if user.is_authenticated %}
        <h4>Вы уже прошли аутентификацию.</h4>
        <a class="btn" href="{% url 'accounts:logout' %}">Выйти</a>
    {% else %}

        <form method="post">
            {% csrf_token %}
            {% include 'includes/form_default.html' %}
            <button class="btn btn-outline-primary" type="submit">Войти</button>
        </form>
    {% endif %}


{% endblock %}

templates/accounts/settings.html
{% extends 'base.html' %}

{% block title %}Настройки{% endblock %}

{% block content %}
    <h2 class="title">Настройки</h2>
    {% if not user.is_authenticated %}
        <h4>Войдите, для доступа к настройкам</h4>
        <a class="btn" href="{% url 'users:login' %}">Войти</a>
    {% else %}

        <form method="post">
            {% csrf_token %}
            {% include 'includes/form_default.html' %}
            <button class="btn btn-outline-primary col-md-2" type="submit">Изенить</button>
        </form>
        <div class="row">
            <a class="link-mod" href="{% url 'courses:users:update_student' %}">Изменить профиль студент</a>
        </div>
    {% endif %}


{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
    Sign Up
{% endblock %}


{% block content %}
    <h2 class="title">Регистрация</h2>
    {% if user.is_authenticated %}
        <h6>Для того, чтобы создать нового пользователя, необходимо выйти из аккаунта.</h6>
        <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Выйти</a>
    {% else %}

        <form action="{% url 'accounts:signup' %}"
              method="post"
              enctype="multipart/form-data"
              class="pure-form pure-form-stacked"
        >
            {% csrf_token %}
            {% include 'includes/form_default.html' %}
            <input type="submit" value="Создать аккаунт" class="form-control btn-primary col-2">
        </form>
    {% endif %}

{% endblock %}