apps/courses/urls.py
from django.urls import path, include
from .views import (
    CourseListView,
    CourseDetailView,
    StudentCourseListView,
    course_enroll,
    LessonListView,
    LessonDetailView
 )


app_name = 'courses'
urlpatterns = [
    path('courses/', CourseListView.as_view(), name='list'),
    path('my_courses/', StudentCourseListView.as_view(), name='my_courses'),
    path('lessons/<slug:slug>', LessonListView.as_view(), name='lessons'),
    path('lessons/<slug:slug>/<slug:lesson_slug>', LessonDetailView.as_view(), name='lesson'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='detail'),
    path('users/', include('apps.course_users.urls', namespace="users")),
    path('enroll/<slug:slug>', course_enroll, name="enroll"),

]

apps/quizzes/urls.py
from django.urls import path
from .views import QuizDetailView, QuizResultView


app_name = 'quizzes'
urlpatterns = [
    path('quiz/<slug:slug>', QuizDetailView.as_view(), name='detail'),
    path('quiz/<slug:slug>/result/', QuizResultView.as_view(), name='result'),
]

it_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from it_courses import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('education/', include('apps.courses.urls', namespace="courses")),
    path('control_panel/', include('apps.control_panel.urls', namespace='control')),
    path('quiz/', include('apps.quizzes.urls', namespace='quiz')),

    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),

    path('', include('apps.main.urls', namespace="main")),

]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

apps/courses/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.db import transaction
from django.utils import timezone
from stdimage import StdImageField

from apps.course_users.models import Teacher, Student
from apps.quizzes.models import Quiz
from apps.quizzes.models import QuizResult
from it_courses.settings import LEVEL, HOMEWORK_SCORE, TEST_SCORE, ATTENDANCE_SCORE, DEADLINE_COEFFICIENT
from utils.img_paths import get_img_path
from utils.shortcuts.for_stdimage import img_files_del

STATES = (
    ('active', 'Курс уже идет'),
    ('close', 'Курс окончен'),
    ('reg', 'Открыт набор на курс'),
)


class Course(models.Model):
    title = models.CharField('Название', max_length=100)
    img = StdImageField(
        "Фотография",
        upload_to=get_img_path,
        variations={'thumb': (400, 225, True)},
        blank=True
    )
    slug = models.SlugField(max_length=20)
    state = models.CharField('статус', choices=STATES, max_length=6)
    max_user_count = models.PositiveSmallIntegerField('Максимальное количество учащихся')
    about = RichTextUploadingField('Описание курса')
    teachers = models.ManyToManyField(Teacher, verbose_name='Учителя')
    students = models.ManyToManyField(Student, verbose_name='Студенты', through='CourseStudent')
    duration = models.CharField('Продолжительность курса', max_length=20)
    start_date = models.DateField('Дата начала курса')
    end_date = models.DateField('Дата завершения курса')

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_lesson_count(self):
        return "%s занятий" % self.lessons.count()


COURSE_STATUS = (
    ('in_view', "На собеседовании"),
    ('active', 'Вам доступен этот курс'),
    ('fail', "Исключен из курса"),
    ('fail_view', "Не прошел собеседование"),
    ('finish', "Окончил курс"),
)


class CourseStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.CharField("Статус", max_length=9, choices=COURSE_STATUS)

    def get_marker(self):
        return {
            'in_view': 'badge-primary',
            'active': 'badge-primary',
            'fail': 'badge-danger',
            'fail_view': 'badge-danger',
            'finish': 'badge-success',
        }.get(self.status, '')

    def get_status_options(self):
        html = ''
        option = '<option value="%s" %s>%s</option>'
        for status in COURSE_STATUS:
            selected = 'selected' if status[0] == self.status else ''
            html += option % (status[0], selected, status[1])
        return html


class LessonQuerySet(models.QuerySet):
    def get_current_lesson(self):
        current = self.filter(date__gte=timezone.now()).first()
        return current or self.last()


class Lesson(models.Model):
    title = models.CharField('Название', max_length=100)
    slug = models.SlugField(max_length=20, blank=True)
    course = models.ForeignKey(Course, 'Курс', related_name='lessons')
    number = models.PositiveSmallIntegerField('Номер занятия', default=1)
    date = models.DateField('Дата занятия', default=timezone.now)
    content = RichTextUploadingField('Материал занятия', blank=True)
    homework = RichTextUploadingField('Домашнее задание', blank=True)
    homework_level = models.PositiveSmallIntegerField('Уровень сложности Домашней Работы', choices=LEVEL, default=3)
    homework_deadline = models.DateField('Дедлайн для домашней работы', blank=True, null=True)
    quiz = models.OneToOneField(Quiz, verbose_name='Тестирование', default=None, blank=True, null=True,
                                on_delete=models.SET_NULL)
    quiz_deadline = models.DateField('Дедлайн для тестирования', blank=True, null=True)

    objects = LessonQuerySet.as_manager()

    class Meta:
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'
        ordering = ['number']

    def have_homework(self):
        if len(self.homework) < 10:
            return False
        return True

    def have_homework_word(self):
        return "Да" if self.have_homework() else "Нет"

    def have_quiz(self):
        if self.quiz is None:
            return False
        return True

    def have_quiz_word(self):
        return "Да" if self.have_quiz() else "Нет"

    def get_student_in_lesson(self, student):
        obj, __ = StudentInLesson.objects.get_or_create(student=student, lesson=self)
        return obj


QUIZ_STATUS = (
    ('on', 'Пройден'),
    ('off', 'Провален'),
    ('not_start', 'Не начат'),
)


class StudentInLesson(models.Model):
    student = models.ForeignKey(Student, verbose_name='ученик', on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, verbose_name='Занятие', on_delete=models.CASCADE)
    attendance = models.BooleanField('Был на занятии', default=False)
    is_homework_final = models.BooleanField('ДЗ сдана', default=False)
    is_homework_in_deadline = models.NullBooleanField('ДЗ сдано в срок', default=None)
    homework_link = models.URLField('Ссылка на ДЗ', blank=True)
    quiz_status = models.CharField('Статус тестирования', max_length=9, default='not_start', choices=QUIZ_STATUS)
    is_quiz_in_deadline = models.NullBooleanField('Тест сдан в срок', default=None)
    quiz_result = models.OneToOneField(QuizResult, 'Результат тестирования', default=None, blank=True, null=True)
    homework_score = models.PositiveSmallIntegerField('Очки за домашнее задание', default=0)
    quiz_score = models.PositiveSmallIntegerField('Очки за тестирование', default=0)

    class Meta:
        verbose_name = 'Студент на занятии'
        verbose_name_plural = 'Студенты на занятиях'

    @transaction.atomic
    def set_quiz_result(self, quiz_result):
        quiz = quiz_result.quiz
        result_percent = quiz_result.get_result_percent()
        student = self.student

        if self.lesson.quiz_deadline and self.lesson.quiz_deadline > timezone.now().date():
            self.is_quiz_in_deadline = True
            deadline_coefficient = DEADLINE_COEFFICIENT
        else:
            self.is_quiz_in_deadline = False
            deadline_coefficient = 1
        if quiz.result > result_percent:
            self.quiz_status = 'off'
            coefficient = 0.5
        else:
            self.quiz_status = 'on'
            coefficient = 1
        self.quiz_score = int(TEST_SCORE * quiz.level * deadline_coefficient * coefficient * result_percent / 100)
        self.quiz_result = quiz_result
        self.save()
        student.score += self.quiz_score
        student.save()

    @transaction.atomic
    def set_homework_result(self, is_final):
        if self.lesson.homework_deadline and self.lesson.homework_deadline > timezone.now().date():
            self.is_homework_in_deadline = True
            deadline_coefficient = DEADLINE_COEFFICIENT
        else:
            self.is_homework_in_deadline = False
            deadline_coefficient = 1
        self.is_homework_final = is_final
        student = self.student
        if is_final:
            self.homework_score = HOMEWORK_SCORE * self.lesson.homework_level * deadline_coefficient
            student.score += self.homework_score
            student.homework_count += 1
        else:
            self.homework_score = 0
            student.score -= HOMEWORK_SCORE * self.lesson.homework_level * deadline_coefficient
            student.homework_count -= 1
        student.save()
        self.save()

    @transaction.atomic
    def set_attendance(self, is_attendance):
        self.attendance = is_attendance
        student = self.student
        if is_attendance:
            student.score += ATTENDANCE_SCORE
        else:
            student.score -= ATTENDANCE_SCORE
        student.save()
        self.save()

    def get_attendance(self):
        return {
            False: 'Не был',
            True: 'Был на занятии',
        }[self.attendance]

    def get_homework_final(self):
        return {
            True: 'Сдано',
            False: 'Не сдано',
        }[self.is_homework_final]

    def get_homework_in_deadline(self):
        return {
            False: 'Нет',
            True: 'Да',
            None: 'Еще не сдана',
        }[self.is_homework_in_deadline]

    def get_quiz_in_deadline(self):
        return {
            False: 'Нет',
            True: 'Да',
            None: 'Тест не начат',
        }[self.is_quiz_in_deadline]

    def checked_homework_final(self):
        if self.is_homework_final:
            return 'checked'
        return ''

    def checked_attendance(self):
        if self.attendance:
            return 'checked'
        return ''


img_files_del(Course)

apps/courses/forms.py
from django import forms

from apps.courses.models import StudentInLesson


class HomeworkLinkForm(forms.Form):
    lesson_id = forms.IntegerField(required=True)
    student_id = forms.IntegerField(required=True)
    link = forms.URLField(required=False)

    def save(self):
        lesson_id = self.cleaned_data['lesson_id']
        student_id = self.cleaned_data['student_id']
        link = self.cleaned_data['link']
        obj = StudentInLesson.objects.get(lesson__id=lesson_id, student__id=student_id)
        obj.homework_link = link
        obj.save()
        return obj

templates/includes/course_state.html
{% if state == 'active' %}
  <p class="badge badge-danger state-badge">Активный</p>
{% elif state == 'reg' %}
  <p class="badge badge-success state-badge ">Открыта регистрация</p>
{% else %}
  <p class="badge badge-secondary state-badge">Курс завершен</p>
{% endif %}

templates/includes/courses.html
{% load course_tags %}

<div class="row">
    {% for course in course_list %}
        <div class="col-lg-4 col-md-6">
            <div class="card  has-text-dark bg-light" style="margin-bottom: 20px">
                <div class="course-header bg-light">
                    <h6 class="text-center card-state">
{#                    {% include 'includes/course_state.html' with state=course.state %}#}
                        {{ course.get_state_display }}
                        {% get_user_badge course %}
                        </h6>
                </div>
                <a href="{% url 'courses:detail' course.slug %}">
                    <img class="card-img-top" src="{{ course.img.thumb.url }}" alt="Card image cap">
                </a>
                <div class="card-body">
                    <a href="{% url 'courses:detail' course.slug %}">
                        <h5 class="card-title text-center">{{ course.title }}</h5>
                    </a>
                    <p class="card-text text-center">
                        <small class="text-dark">Начало курса: {{ course.start_date }}</small>
                    </p>
                    {% get_course_button course %}
                    <div class="row bottom-info">
                        <p class="col-md-6 text-left">{{ course.duration }}</p>
                        <p class="col-md-6 text-right">{{ course.get_lesson_count }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <row>
            <h5 class="col-md-12">Нет курсов данной категории</h5>
        </row>
    {% endfor %}
</div>

templates/includes/form_default.html
{% load class_atr_for_field %}

{% if form.errors %}
    {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-3 ">
                {{ field.label }}:
            </label>
            {% if field.errors %}
                {{ field|add_class:'form-control col-6 is-invalid'}}
            {% else %}
                {{ field|add_class:'form-control col-6 is-valid'}}
            {% endif %}

            {% for error in field.errors %}
                <div class="invalid-feedback col-12">
                    {{ error }}
                </div>
            {% endfor %}

            {% if field.help_text %}
                <small class="text-muted col-12">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-3">{{ field.label }}:</label>
            {{ field|add_class:'form-control col-6'}}
            {% if field.help_text %}
                <small class="text-muted col-12">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

templates/includes/lesson_content.html
{% load lesson_tags class_atr_for_field %}

{% if not lesson is None %}

    {% get_student_in_lesson lesson user.student as student_in_lesson %}

    {% for less in lesson_list %}
        <a class="badge {% if less.id == lesson.id %}badge-success{% else %}badge-secondary{% endif %}"
           href="{% url 'courses:lesson' course_slug less.slug %}"
        >{{ less.number }}</a>
    {% endfor %}


    <h3 class="text-center">{{ title }} {{ lesson.number }} - {{ lesson.title }}</h3>
    <br>
    <p><strong>Дата проведения:</strong> {{ lesson.date }}</p>
    <p><strong>Посещение:</strong> {{ student_in_lesson.get_attendance }}</p>

    {% if lesson.have_quiz %}
        <br>
        <h4>Тестирование</h4>
        <p><strong>Статус: </strong>{{ student_in_lesson.get_quiz_status_display }}</p>
        <p><strong>Дедлайн: </strong>{{ lesson.quiz_deadline }} </p>
        <p><strong>В срок: </strong>{{ student_in_lesson.get_quiz_in_deadline }}</p>
        <p><strong>Балов набрано: </strong>{{ student_in_lesson.quiz_score }}</p>
        {% if student_in_lesson.quiz_status == 'not_start' %}
            <p><a class="btn btn-outline-success" href="{% url 'quiz:detail' lesson.quiz.slug %}">Пройти тест</a></p>
        {% else %}
            <p><a class="btn btn-outline-success" href="{% url 'quiz:result' lesson.quiz.slug %}">Посмотреть результаты</a></p>
        {% endif %}

    {% endif %}

    {% if lesson.have_homework %}
        <br>
        <h4>Домашнее задание</h4>
        <p><strong>Статус: </strong>{{ student_in_lesson.get_homework_final }}</p>
        <p><strong>Дедлайн: </strong>{{ lesson.homework_deadline }} </p>
        <p><strong>В срок: </strong>{{ student_in_lesson.get_homework_in_deadline }}</p>
        <p><strong>Балов набрано: </strong>{{ student_in_lesson.homework_score }}</p>
        <p>
        <form>
            <strong>Ссылка на репозиторий: </strong>
            {% csrf_token %}
            <input style="display: none" type="number" name="lesson_id" required=""
                   value="{{ lesson.id }}">
            <input style="display: none" type="number" name="student_id" required=""
                   value="{{ user.student.id }}">
{#            {{ form.link }}#}
            <input type="url" name="link" id="id_link" class="form-control col-md-3" value="{{ student_in_lesson.homework_link }}">
            <a href="#save-link" class="js-ajax-send text-center">Изменить</a>
        </form>
        </p>
        <p><strong>Задание: </strong>{{ lesson.homework|safe }}</p>


    {% endif %}

    <br>
    <h4>Учебный материал</h4>
    {{ lesson.content|safe }}
{% endif %}

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
             <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
    {% endfor %}
{% endif %}


<div style="display: none; position: fixed; right: 0" class="alert ajax-alert  alert-dismissible fade show" role="alert">
    <strong class="text-center"></strong>
</div>

templates/includes/pagination.html
{% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col-12">
                {% if page_obj.has_previous %}
                    <a class="badge badge-info" href="?page=1">&laquo; в начало</a>
                    <a class="badge badge-info" href="?page={{ page_obj.previous_page_number }}">назад</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="badge badge-info" href="?page={{ page_obj.next_page_number }}">вперед</a>
                    <a class="badge badge-info" href="?page={{ page_obj.paginator.num_pages }}">в конец &raquo;</a>
                {% endif %}
        </div>
    </div>
{% endif %}

templates/includes/quiz_info.html
<h4>Информация</h4>
<br>
<p>
    <a href="{% url 'courses:lesson' quiz.lesson.course.slug quiz.lesson.slug %}">
        <i class="fas fa-arrow-alt-circle-left"></i>
        Вернуться к Занятию
    </a>
</p>
<p><strong>Дедлайн: </strong>{{ quiz.lesson.quiz_deadline }} </p>
<p><strong>Необходимый процент правильных ответов: </strong>{{ quiz.result }} % </p>
<p><strong>Количество вопросов: </strong>{{ quiz.questions.count }}</p>