apps/accounts/urls.py
from django.urls import path, re_path
from .views import SignUpView, AccountUpdateView, logout_view, activate, send_activation_email
from django.contrib.auth.views import LoginView


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    re_path(
        r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate,
        name='activate'
    ),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('send_activation_email/', send_activation_email, name='send_activation_email'),
    path('settings/', AccountUpdateView.as_view(), name='settings'),
]

apps/control_panel/urls.py
from django.urls import path
from .views import StudentSelectionCPView, StudentVisitCPView, StudentHomeworkCPView


app_name = 'control_center'
urlpatterns = [
    path('selection/<slug:slug>', StudentSelectionCPView.as_view(), name='selection'),
    path('visit/<slug:slug>/', StudentVisitCPView.as_view(), name='visit_current'),
    path('visit/<slug:slug>/<slug:lesson_slug>', StudentVisitCPView.as_view(), name='visit'),
    path('homework/<slug:slug>/', StudentHomeworkCPView.as_view(), name='homework_current'),
    path('homework/<slug:slug>/<slug:lesson_slug>', StudentHomeworkCPView.as_view(), name='homework'),
]

apps/courses/urls.py
from django.urls import path, include
from .views import (
    CourseListView,
    CourseDetailView,
    StudentCourseListView,
    course_enroll,
    LessonListView,
    LessonDetailView
 )


app_name = 'courses'
urlpatterns = [
    path('courses/', CourseListView.as_view(), name='list'),
    path('my_courses/', StudentCourseListView.as_view(), name='my_courses'),
    path('lessons/<slug:slug>', LessonListView.as_view(), name='lessons'),
    path('lessons/<slug:slug>/<slug:lesson_slug>', LessonDetailView.as_view(), name='lesson'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='detail'),
    path('users/', include('apps.course_users.urls', namespace="users")),
    path('enroll/<slug:slug>', course_enroll, name="enroll"),

]

apps/main/urls.py
from django.urls import path
from .views import HomeView, PageDetailView


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<slug:slug>', PageDetailView.as_view(), name='page'),

]

it_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from it_courses import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('education/', include('apps.courses.urls', namespace="courses")),
    path('control_panel/', include('apps.control_panel.urls', namespace='control')),
    path('quiz/', include('apps.quizzes.urls', namespace='quiz')),

    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),

    path('', include('apps.main.urls', namespace="main")),

]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

templates/base_includes/header.html
{% load menu_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ITCourses</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% url 'main:home' as url %}
            <li class="nav-item {% is_base_url_active 'main' %}">
                <a class="nav-link" href="{{ url }}">Главная</a>
            </li>
            {% url 'courses:list' as url %}
            <li class="nav-item {% is_base_url_active 'course' %}">
                <a class="nav-link" href="{{ url }}">Курсы</a>
            </li>
            {% if user.is_active_student %}
                {% url 'courses:lessons' user.student.get_first_course.slug as url %}
                <li class="nav-item {% is_base_url_active 'lesson' %}">
                    <a class="nav-link" href="{{ url }}">Занятия</a>
                </li>
            {% endif %}
            {% if user.is_teacher %}
                <li class="nav-item dropdown {% is_base_url_active 'control' %}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Панель управления
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                        <a class="dropdown-item" href="{% url 'control:selection' user.teacher.get_first_course.slug %}">Статусы студентов</a>
                        <a class="dropdown-item" href="{% url 'control:visit_current' user.teacher.get_first_course.slug %}">Посещения</a>
                        <a class="dropdown-item" href="{% url 'control:homework_current' user.teacher.get_first_course.slug %}">Домашние задания</a>
                    </div>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                {% if not user.email_confirmed %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:send_activation_email' %}">Подтвердить почту</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user fa-lg"></i> {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

                        {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:settings' %}">Настройки</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Регистрация</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>