apps/courses/urls.py
from django.urls import path, include
from .views import (
    CourseListView,
    CourseDetailView,
    StudentCourseListView,
    course_enroll,
    LessonListView,
    LessonDetailView
 )


app_name = 'courses'
urlpatterns = [
    path('courses/', CourseListView.as_view(), name='list'),
    path('my_courses/', StudentCourseListView.as_view(), name='my_courses'),
    path('lessons/<slug:slug>', LessonListView.as_view(), name='lessons'),
    path('lessons/<slug:slug>/<slug:lesson_slug>', LessonDetailView.as_view(), name='lesson'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='detail'),
    path('users/', include('apps.course_users.urls', namespace="users")),
    path('enroll/<slug:slug>', course_enroll, name="enroll"),

]

apps/main/urls.py
from django.urls import path
from .views import HomeView, PageDetailView


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<slug:slug>', PageDetailView.as_view(), name='page'),

]

it_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from it_courses import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('education/', include('apps.courses.urls', namespace="courses")),
    path('control_panel/', include('apps.control_panel.urls', namespace='control')),
    path('quiz/', include('apps.quizzes.urls', namespace='quiz')),

    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),

    path('', include('apps.main.urls', namespace="main")),

]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

templates/bases/course_base.html
{% extends 'base.html' %}
{% load menu_tags %}

{% block second_header %}
    <div class="second_header">
        <h5 class=" second_header_h">Курсы</h5>
        <ul class="nav ">
            <li class="nav-item">
                {% url 'courses:list' as url %}
                <a class="nav-link {% is_url_active url %}" href="{{ url }}">Курсы</a>
            </li>
            {% if user.is_active_student %}
                <li class="nav-item">
                    {% url 'courses:my_courses' as url %}
                    <a class="nav-link {% is_url_active url %}" href="{{ url }}">Мои курсы</a>
                </li>
            {% endif %}
            <li class="nav-item">
                {% url 'courses:users:teachers' as url %}
                <a class="nav-link {% is_url_active url %}" href="{{ url }}">Преподаватели</a>
            </li>
            <li class="nav-item">
                {% url 'courses:users:students' as url %}
                <a class="nav-link {% is_url_active url %}" href="{{ url }}">Студенты</a>
            </li>
        </ul>
    </div>
    <br>
    <br>
{% endblock %}

templates/bases/home_base.html
{% extends 'base.html' %}
{% load menu_tags %}

{% block second_header %}

    <div class="second_header">
        <h5 class="second_header_h">Главная</h5>
        <ul class="nav">
            <li class="nav-item">
                {% url 'main:home' as url %}
                <a class="nav-link {% is_url_active url %}" href="{{ url }}">Общая информация</a>
            </li>
            {% for page in pages %}
                <li class="nav-item">
                    {% url 'main:page' page.slug as url %}
                    <a class="nav-link {% is_url_active url %}" href="{{ url }}">{{ page.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <br>
    <br>
{% endblock %}

templates/bases/others_base.html
{% extends 'base.html' %}
{% load menu_tags %}

{% block second_header %}
    <div class="second_header">
        <h5 class="second_header_h">{{ menu_title }}</h5>
        <ul class="nav ">

            {% with menu_courses.count as courses_count %}
                {% for course in menu_courses %}
                    <li class="nav-item">
                        {% url url_name course.slug as url %}
                        <a class="nav-link {% is_url_active url %}" href="{{ url }}">{{ course.title }}</a>
                    </li>

                {% endfor %}
            {% endwith %}
        </ul>
    </div>
    <br>
    <br>
{% endblock %}